### ISSUE TITLE
Weather Commands

### ISSUE THREAD

**Issue by SaltSouls** [lukebemishprojects/Tempest#32]
Hi, really love the mod idea, but there is on slight issue right now. Tempests weather conditions are not linked to the vanilla weathers, so when changing the weather to clear, Tempest will continue to pour rain or snow outside. I would suggest either having tempest be respect general weather commands, or at least have mod specific commands for changing tempest weather conditions. I mean, you could even just hook into the normal weather events and make a percent chance for certain tempest weathers when said weather event is triggered(assuming this isn't how this is already working). That way tempest weathers just override vanillas when called, and mods/players should be able to set/reset weather conditions when needed.

**Comment by lukebemish** [comment]
This is intentional behavior. Unlike vanilla weather, weather in Tempest is regional - in other words, it can be raining in some areas while clear in others. Thus, it doesn't make sense for `/weather clear` to do anything - there is no state where the weather is ever clear _everywhere_! The system is entirely independent from the vanilla weather system - if you would like to avoid overlaps between the two, you can disable the vanilla weather via gamerule.

That said, I do have plans to add some custom commands that act as better debugging tools when integrated with the right datapack, but there will likely not be integration with the vanilla commands simply due to it really making no sense whatsoever.
