### ISSUE TITLE
No commands / can't use weather commands

### ISSUE THREAD

**Issue by PaulRV0709** [lukebemishprojects/Tempest#44]
Hey there,

The weather commands don't seem to affect the mod. Is that a feature? Are there commands to change the weather?

**Comment by lukebemish** [comment]
This is intentional behavior. Unlike vanilla weather, weather in Tempest is regional - in other words, it can be raining in some areas while clear in others. Thus, it doesn't make sense for /weather clear to do anything - there is no state where the weather is ever clear everywhere! The system is entirely independent from the vanilla weather system - if you would like to avoid overlaps between the two, you can disable the vanilla weather via gamerule.

That said, I do have plans to add some custom commands that act as better debugging tools when integrated with the right datapack, but there will likely not be integration with the vanilla commands simply due to it really making no sense whatsoever.
